name: Build (Linux)

runs:
  using: composite

  steps:
    - name: Build
      run: |
        cmake -S . -B build
        cmake --build build --config Release
        cpack -B build --config build/CPackConfig.cmake
      shell: bash
