name: Build (Windows MSVC)

runs:
  using: composite
  
  steps:
    - name: Build
      run: |
        cmake -S . -B build -G "Visual Studio 17 2022"
        cmake --build build --config Release
        cpack -B build --config build/CPackConfig.cmake
      shell: bash
