name: Create release

on:
  push:
    branches: main
    tags: v*

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      
      - run: |
          ls -A
          ls -A .github
          ls -A .github/actions
          ls -A .github/actions/test-action

      - name: test composite action
        uses: ./.github/actions/test-action

      - name: Add assets to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REF: ${{ github.event.push.ref }}
        run: |
          ls
#					tag = ${REF##*/}
#					gh release create "$tag" "hexspin/build/hexspin-${tag#v}-win64.zip" \
#						--repo="$GITHUB_REPOSITORY" \
#						--title="${GITHUB_REPOSITORY##*/} ${tag#v}" \
#						--generate-notes
