name: Create release

on:
  push:
    branches: main
    tags:

jobs:
  thing:
    runs-on: ubuntu-latest
    
    steps:
      - env:
          ref: ${{ github.ref }}
        run: echo "${ref}"

  build-windows-msvc:
    name: Windows (MSVC)
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022"
          cmake --build build --config Release
          cpack -B dist --config build/CPackConfig.cmake
        shell: bash
      
      - name: Upload as artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: dist/*.zip
          retention-days: 3
  
  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Install dependencies
        run: sudo apt install xorg-dev

      - name: Build
        run: |
          cmake -S . -B build
          cmake --build build --config Release
          cpack -B dist --config build/CPackConfig.cmake

      - name: Upload as artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: dist/*.zip
          retention-days: 3

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [build-windows-msvc, build-linux]
    permissions: write-all
    
    steps:
      - name: Download assets
        uses: actions/download-artifact@v3
        id: download
        with:
          path: dist
      
      - run: ls -R
        working-directory: dist

      - name: Add assets to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" dist/*/*.zip \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY##*/} ${tag#v}" \
            --generate-notes \
            --prerelease
