on: push

jobs:
  test:
    runs-on: windows-latest
    steps:
      - run: git clone https://github.com/glfw/glfw.git
      - run: cmake -S glfw -B glfw/build -G "Visual Studio 17 2022"
      - run: cmake --build glfw/build --parallel
      - run: ls glfw
      - run: ls glfw/build
