on: push

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Restore GLFW files from cache
        id: cache-glfw
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-glfw-build
          path: |
            glfw/include
            glfw/build/src/Debug/glfw3.lib

      - name: Build GLFW
        if: ${{ steps.cache-glfw.outputs.cache-hit != 'true' }}
        run: |
          git clone https://github.com/glfw/glfw.git
          cd glfw && git checkout latest && cd ..
          cmake -S glfw -B glfw/build -G "Visual Studio 17 2022" -D GLFW_BUILD_EXAMPLES=OFF -D GLFW_BUILD_TESTS=OFF -D GLFW_BUILD_DOCS=OFF
          cmake --build glfw/build --parallel

      - uses: actions/checkout@v3
        with:
          path: hexspin

      - name: Compile
      - run: |
          gcc -o build/main src/*.c -Iinclude -I../glfw/include -L../glfw/build/src/Debug/glfw3.lib -lglfw -lm
        working-directory: hexspin
