on: push

jobs:
  windows-mingw:
    name: Windows (MinGW)
    runs-on: windows-latest
    permissions: write-all
    
    steps:
      - name: Restore GLFW files from cache
        id: cache-glfw
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-glfw-mingw
          path: |
            glfw/include
            glfw/build/src/libglfw3.a

      - name: Build GLFW
        if: ${{ steps.cache-glfw.outputs.cache-hit != 'true' }}
        run: |
          git clone https://github.com/glfw/glfw.git
          cd glfw && git checkout latest && cd ..
          cmake -S glfw -B glfw/build -G "MinGW Makefiles" -D GLFW_BUILD_EXAMPLES=OFF -D GLFW_BUILD_TESTS=OFF -D GLFW_BUILD_DOCS=OFF
          cmake --build glfw/build --parallel

      - uses: actions/checkout@v3
        with:
          path: hexspin

        # TODO: figure out how to compile with visual studio (msvc?), probably with cmake
      - name: Compile
        run: |
          mkdir build
          gcc -o build/main src/*.c -Iinclude -I../glfw/include ../glfw/build/src/libglfw3.a -lm -lgdi32
          tree . /F
        working-directory: hexspin
      
      - name: Compress binary
        run: Compress-Archive hexspin/build hexspin/build.zip
      
      - name: Add binary to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: v1.0.0-beta
        shell: bash
        run: |
          gh release upload "$tag" "hexspin/build.zip#${GITHUB_REPOSITORY##*/}-$tag.zip" \
            --repo="$GITHUB_REPOSITORY" \
            --clobber
